### ISSUE TITLE
few bugs in the new code.

### ISSUE THREAD

**Issue by alevin** [gwhs/Robot2023-V2#39]
@Bennables , I run sonar check against new code and I suspect that reported bugs should be easy to fix and avoid in the future.
They might be not very critical, but please take a look:

https://sonarcloud.io/project/issues?resolved=false&types=BUG&sinceLeakPeriod=true&id=gwhs_Robot2023-V2

@RobertTheBlair , does it make sense to you ? 

Thanks
--Alex

**Comment by RobertTheBlair** [comment]
Fixed

**Comment by RobertTheBlair** [comment]
Mostly fixed?
