### ISSUE TITLE
choose auto on shuffleboard

### ISSUE THREAD

**Issue by Bennables** [gwhs/Robot2023-V2#42]

**Comment by alevin** [comment]
As an example you can look at code at https://github.com/wpilibsuite/allwpilib/blob/main/wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/hatchbotinlined/RobotContainer.java

https://docs.wpilib.org/en/stable/docs/software/dashboards/smartdashboard/choosing-an-autonomous-program-from-smartdashboard.html#setting-up-sendablechooser

**Comment by Juzhu2** [comment]
Finished with rob - wilson
