### ISSUE TITLE
Weird behavior of swerve modules in autonomous

### ISSUE THREAD

**Issue by alevin** [gwhs/Robot2023-V2#44]
Figure out the reason and fix shaking behavior of swerve modules during autonomous mode.
As it is similar on different robots (Hana with MK4, navx and Chris with MK4i , pigeon2) - most likely it is is the code.

Could be some PID loop or odometry/pose estimate or something else.

**Comment by RobertTheBlair** [comment]
Two commands were fighting for control, and were both issuing commands to the drivetrain

**Comment by RobertTheBlair** [comment]
PR fixed the issue
